{% set name = "dvc-s3" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ea72c9b6b000dfea1a834d4106733b6cdc745d0a6ee1d5c0a5b8c8344671716

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >={{ python_min }}
    - dvc
    - s3fs >=2021.11.0
    - boto3 >=1.9.201

test:
  imports:
    - dvc_s3
  requires:
    - git
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - dvc version
    - dvc version | grep s3

about:
  home: https://github.com/iterative/dvc-s3
  summary: Amazon S3 plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
